DATASET:

  train_batch_size: 128





MODEL:
  inout_branch: False


TRAIN:
  maxlr: 1e-4

  stage: 1

  resume: True
  resume_add: "/home/extend/hzx/VSGIA&ablation/damreplement/gazefollow/dam_gf_99epoch.pth.tar"

  store: "./modelparas"

  save_intervel: 1

  end_epoch: 41

OTHER:

  lossrec_every: 50

  evalrec_every: 400