DATASET:
  root_dir: "/home/hzx/dataset/videoattentiontarget"
  train_anno: "/home/hzx/dataset/videoattentiontarget/train_dam.txt"
  test_anno: "/home/hzx/dataset/videoattentiontarget/test_dam.txt"

  train_batch_size: 128
  test_batch_size: 128

MODEL:
  inout_branch: True

TRAIN:
  maxlr: 1e-4

  stage: 2

  resume: True
  resume_add: "/home/extend/hzx/VSGIA&ablation/damreplement/videoatt/dam_vat_0epoch.pth.tar"

  initmodel: False
  initmodel_add: "/home/extend/hzx/VSGIA&ablation/damreplement/videoatt/dam_videoattstart.pth.tar"

  store: "/home/extend/hzx/VSGIA&ablation/damreplement/videoatt"

  save_intervel: 1

  end_epoch: 10

OTHER:

  lossrec_every: 50

  evalrec_every: 600