DATASET:
  root_dir: "../datasets/videoattentiontarget"
  train_anno: "../datasets/videotargetattention_annotations/train_annotation_dam.txt"
  test_anno: "../datasets/videotargetattention_annotations/test_annotation_dam.txt"
  depth_dir: "../datasets/videotargetattention_depthnp/"

  train_batch_size: 128
  test_batch_size: 128

MODEL:
  inout_branch: True

TRAIN:
  maxlr: 1e-4

  stage: 2

  resume: False
  resume_add: ""



  store: "./modelparas"

  save_intervel: 1

  end_epoch: 10

OTHER:

  lossrec_every: 50

  evalrec_every: 600